language: rust
sudo: required
os: linux
cache: cargo

addons:
  apt:
    packages:
      - libssl-dev

before_install:
  # Because we cached Cargo packages, installing "tarpaulin" may fail with
  # "already exists" error. So we added "||true" to prevent failure of the
  # CI process.
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin ||true

# TODO: For now, we only report coverage of Emulator. We should accumulate all coverages.
script:
  - echo "Building emulator"
  - cd emulator
  - cargo build
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  - echo "Building compiler"
  - cd ../compiler/
  - cargo build
  - cargo test
  - echo "Building employees"
  - cd ../employees/
  - cargo build
  - cargo test
