language: rust
sudo: required
os: linux
cache: cargo

addons:
  apt:
    packages:
      - libssl-dev

before_install:
  # Because we cached Cargo packages, installing "tarpaulin" may fail with
  # "already exists" error. So we added "||true" to prevent failure of the
  # CI process.
  - cargo install cargo-tarpaulin ||true

script:
  - echo "Building emulator"
  - cd emulator
  - cargo build
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  - echo "Building compiler"
  - cd ../compiler/
  - cargo build
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

