[package]
name = "compiler"
version = "0.1.0"
authors = ["Aidin Gharibnavaz <aidin@aidinhut.com>"]
description = "Compiler for the assembly language."
license = "GPLv3"
# Preventing accedental publishing on crates.io
publish = false

[dependencies]
